version: '3.8'

services:
  db:
    image: postgres:15
    container_name: tasklist-db
    restart: always
    ports:
      - "6001:5432"
    environment:
      POSTGRES_DB: tasklistdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
