name: Build, Test, and Deploy 

on:
  push:
    branches: [ main ]

env:
  IMAGE_NAME: miixo22/springbootapi-app
  CONTAINER_NAME: springboot-app
  APP_PORT: 8080

jobs:
  # 1️⃣ Build and Test on GitHub-hosted runner
  build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build and test with Maven
        run: mvn clean verify

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .
          docker push $IMAGE_NAME:latest

  # 2️⃣ Deploy on your Ubuntu VM (self-hosted runner)
  deploy:
    needs: build_and_push
    runs-on: self-hosted
    steps:
      - name: Pull and run the container
        run: |
          echo "Logging into Docker..."
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

          echo "Pulling latest image..."
          docker pull $IMAGE_NAME:latest

          echo "Stopping old container..."
          docker stop $CONTAINER_NAME || true
          docker rm $CONTAINER_NAME || true

          echo "Starting new container..."
          docker run -d \
            --name $CONTAINER_NAME \
            -p 8080:8080 \
            $IMAGE_NAME:latest
